/*
 * Created on 2017-03-22 ( Date ISO 2017-03-22 - Time 17:28:47 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */

package org.demo.persistence.commons;

/**
 * The pattern defined here is used by the Persistence Service Provider <br>
 * to build the service implementation class name <br>
 * 
 * @author Telosys
 *
 */
public class PersistenceMongoServicePattern {

	public final static String  PATTERN = "%s.impl.mongo.%sImplMongo" ;	
}
